### ISSUE TITLE
Error "No changes!"

### ISSUE THREAD

**Issue by Pelesa** [OctoPrint/OctoPrint-Yamlpatcher#5]
Good morning,
Recently I installed a BLtouch on my Ender3, when connecting the cables the screen operation is lost (But the bltouch works correctly) so I need to edit the Z offset from Octoprint to be able to print.
I found this [code](https://www.kodamaforums.com/phpBB3/viewtopic.php?t=2060), and I wanted to implement it with the plugging but I get a message that there have been no changes.

controls:
- children:
  - command: M628
    default: ''
    name: Get
    regex: z zero offset value:(?P<offset>\d+(\.\d*))
    template: 'Current: {offset} mm'
    width: '5'
  - command: M628 Z%(offset)s
    input:
    - default: '0.00'
      name: New (mm)
      parameter: offset
      slider: false
    name: Set
    width: '5'
  - command: G28 Z0
    name: Home Z
    width: '2'
  collapsed: true
  layout: horizontal_grid
  name: Adjust Z Offset

![image](https://user-images.githubusercontent.com/53566770/62292761-6fb0ce00-b467-11e9-8d13-b944fa23d07e.png)

Thank you very much for your help.

**Comment by foosel** [comment]
That's too complex for the yaml patcher to merge, you'll need to go with the json format for this.

For adding custom controls I'd rather recommend to use the [dedicated plugin](https://plugins.octoprint.org/plugins/customControl/) however.
